kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  extraPortMappings:
  - containerPort: 30000
    hostPort: 80
    listenAddress: "0.0.0.0"
  - containerPort: 30001
    hostPort: 443
    listenAddress: "0.0.0.0"
  - containerPort: 30002
    hostPort: 15021
    listenAddress: "0.0.0.0"
  - containerPort: 30003
    hostPort: 8080
    listenAddress: "0.0.0.0"
  - containerPort: 30004
    hostPort: 8081
    listenAddress: "0.0.0.0"
  extraMounts:
  # FOR DOCKER CONFIG FILE
  - hostPath: /home/ec2-user/config.json
    containerPath: /var/lib/kubelet/config.json
  # FOR NODE DATA
  - hostPath: /tmp
    containerPath: /data
